server:
  port: 8080

kafka:
  topic: orderTaobao

spring:
  kafka:
    bootstrap-servers: localhost:9091, localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer